language: node_js
sudo: false
node_js:
  - stable

before_script:
  - npm install grunt-cli -g

install:
  - npm install -g bower
  - bower install
  - npm install
script: grunt

after_success:
  - bash deploy.sh

env:
  global:
  - GH_REF: github.com/matt3188/flipCard
  - secure: btT7wIXN2wZs2HZKTTWfx7y5S8EBs/LhF7H3HtDtFPFA9LRcp5UC39bxWu+JU4ScPemmL7HCtwf8GCvn8wz2AoHxHxAK1Y/NFGx66zn8toYZV5Zi9MfO7fKwjTozVe7SJ1z8gOEwMisTiokQ1XT0szEWBzLvMoQ3TYmXG4XZrAsD2eJttQ/xDowJdFqginBXFhnutn8nSLnZqjrNR01M7qDJP+GuGLPX1N8XzCjOljiRWfDaxARahYdym/8nEH5Yu9jAfUdvseCBcIZRBR1eYMjiPhd2LLW+El54AkHx+tDR32pHQo2yewhz6MtL7tKOzfleJngxhnPcsIZhZtkPiHYKRLJlmu6KM1u0cYsEF+mYZ2i2Mv90Kp/xb5cF34L7kFOiFyx1w0+zTIDsZfoZf36MG0liKw2L9k6SvJTpvydJ2sa2NsCvSUZmS7VHEkHpJLol3ey+99IMBG5yC+qvYJ86GxIG6fFkIM6plzJoApqVgP5JHFeQdwEaYZTYE0yZG1f8wouePb1az61GqZDMsQcYOyIW+CnwxVDkjsqfr5w2MWgAOUJtMfxpmuBqrSHXhtyMgnGmKliNomekkrDeukg0lyc0qdXs18Y/q2v3haTqNKX8eCMeE7d5uRra2Zrv15c8AIuODStpj2cIQZsXJAU8Bg9Tx74bqiqWuGl5M/A
