language: node_js
sudo: false
node_js:
  - stable

before_script:
  - npm install grunt-cli -g

install:
  - npm install -g bower
  - bower install
  - npm install
script: grunt

after_success:
  - bash deploy.sh

env:
  global:
  - GH_REF: github.com/matt3188/flipCard
  - secure: "lcuiyi2dFZG2FhHlz7bFzFBSg/VZgCoZBEOelgLnXnE6/ZBPL4BRFM+1WHPLnSR93Kgewu/fiiqK84S3eSMWT1lSFKe+hKqw/n0DKeQ2mrV6X/+UM9Ckr041EnfpEnw+qDNBKQ6XUgoPMMsZK9q+rGlFvS0TlVFrbG2dAQpXISptnV69sMekBg1rrJe/QKOKl28k4UbK3YUEGvJYMcTAcr2wl5CrQs/6qvHVJty7Nyap1JcaYtdUjoMf8eoNfk3ebq7YcUJZbP+tk82AxWLlPpEnvHFtD/o50Kw5oVNLJLVOH2+82Qi7/lgNXgSsYkhBTJ6zwp2bgy80KPyeUg2LU3tuWdPyygSl8kq0V6G3lULgB5b02Oo7KYO/H6b9PPlWNS+aJMKKpGmUbxsHlGXbGWP3scEmUQx1IvEb1jduIQi9vDHwbu1fEKprV+NqovI2LlHTUZup57mkL/o0Ys2lePxgiXsykr8MrzFUyGwCuHXBejrmnLQJlqjULEc6ymBHbSOKZb83u8kanWMg+0lug0sVh05ycRG0i4jQlDIWqIBz5R5L2KYN+9veWIXrGyT2n6ZZPKR4wj0HmvcQXbiBd82zaURDZPZGAKfJqL2x1pXPRt55t8GpH+ebFMSOEaVpWx/wHClaIfWUPi7cHridOhjcDeQ+DZ0IhZO8lzRr0EM"
