language: node_js
sudo: false
node_js:
  - 'stable'

before_script:
- npm install grunt-cli -g

install:
- npm install -g bower
- bower install
- npm install
script: grunt

after_success:
  - bash deploy.sh

