language: node_js
sudo: false
node_js:
  - 'stable'

before_script:
- npm install grunt-cli -g

install:
- npm install -g bower
- bower install
- npm install
script: grunt

after_success:
  - bash deploy.sh

env:
  global:
  - GH_REF: github.com/matt3188/flipCard
  - secure: YD0rgbykCttZRBBhCM7aPUA7BFWFrcvItAWTlVKTXlxiN2SWg1m7dOaL71HTXnVPPfSrtLa070h5I8b2MldN0vt9O2WQyQiYePYrHdS2jRme5VoULtM6/ABY78QQAcVp5/vllnFPGZdgUwUD/QyhF5yb13DtGRU71jiJbZLgkSYt4PyOKlHUSDYu+tWnpmcgfMmNgykPa+U8ju9JS2UNW7yUmELmpFxt/iBlDsEkTUIwb6n6CJdNbUfzNQBULFlV8Aj3l2I3gG4ZYen/t0mW3auBNbqqxB3gsGMDpQ3/e2BRXckPVz/jbi+ady24s/CfrMC1jpYySDhhT8DVxlJZKH6meGob9ibZZnZh+V4LWuDRbaOGHQl6EYzpjhtSkQvFCpjeBrL910cvpoUn2sC4x+xWHPYsKJNicVLEtJ3OVtTZHpWzitipMrQvW3WyDm3jx0MuBaYZ9cz21/Q9CR5NYM2mZvVvWdgresOBPhu8EFyAwEIcZqGxW+waG8nCDaki+xoiCNBFV7qOHPNbynqyFnPxDytfp+5Aj03xHplNpC7OzSEGJM+JMCNjuz0zlV+dpcN5nbF/9SKZEDOVkEpmU7pUMoqKk+4NWZTM8dk94rzBQ3L9wpon5rEDpqkUXPTw5cKq7hjDJn9kQkL7NFZkgaks6lZtPdWktGrTlsyoocs
