language: node_js
sudo: false
node_js:
  - stable

before_script:
  - npm install grunt-cli -g

install:
  - npm install -g bower
  - bower install
  - npm install
script: grunt

after_success:
  - bash deploy.sh

env:
  global:
  - GH_REF: github.com/matt3188/flipCard
  - secure: paUc4tjen2a3uG+u4czlnRt/lo2leyd8WT885Aou7l5zFTyfbBgzXeZUEOO5lDuqFy6bxZbSQfyMDPeUg76M0zLi/loAuCbMoO3ABYog66pwhDZWoLsTO+hfgCdGDepF2rMhwbV4/LLmxyGHlzNLsYZZUuTifLrYFauJCmTMvcFkX1usJJQkmXc0uka6XPV/0Pl/HFnbWmAAixUaASWb81Y+c6yj5L+Q2i3qrgAGE/o/kRHlRCCj1v2J4qnDlqGTkvO9rnzB4bhJAl81bqJabDX4/b1lgRJ+yhK8OgHMiWjwEO+0hvBwPDtNzP/nk+grnQ9TcTfTWc+LbZYlXc+w/hRk/HDHi60Pi60x48/O5V++m0/U4ScaVk4GrnGueKuNvwOXsmdHhMplNXqi12uF73hpSZ/fzh9AWEqNDJcVtdV4iEIneEnAyzH7qVQuBQfHYCdN2qv8NoifFkcaBKy3rtoiD9Qvh+w4yiSvTJ8SmBUj953UfiEi0cq5enn2Lm2wbqF25sfVZrmBJww4zr3zj3dnZjXdd0XIIYey3xGT8mJ/aIZAmcqxMgskVdDcSrL1ow1ffL/FWR43ixgsqcqMyFdRH+99z65pz5KOM3O01u/3+X+lOgNFqsTxkkLAiSVFg0n8uqUx8n408hJRhm3BNgDNt1YLdXfZ+rZDKhKHlRw=
